server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: cliente-service
              uri: lb://cliente-service
              predicates:
                - Path=/api/v1/clientes/**
            - id: clientes-service-typo-override
              uri: lb://cliente-service
              predicates:
                - Path=/CLIENTES-SERVICE/**
              filters:
                - RewritePath=/CLIENTES-SERVICE/(?<segment>.*), /${segment}
            - id: pedidos-service
              uri: lb://pedidos
              predicates:
                - Path=/api/v1/pedidos/**
            - id: pagos-service
              uri: lb://pagos
              predicates:
                - Path=/api/v1/pagos/**
            - id: envios-service
              uri: lb://envios
              predicates:
                - Path=/api/v1/envios/**
            - id: notificaciones-service
              uri: lb://notificaciones
              predicates:
                - Path=/api/v1/notificaciones/**
            - id: inventariov-service
              uri: lb://inventariov
              predicates:
                - Path=/api/v1/videojuegos/**
            - id: inventariof-service
              uri: lb://inventariof
              predicates:
                - Path=/api/v1/f1/**
            - id: promociones-service
              uri: lb://promociones-service
              predicates:
                - Path=/api/promociones/**
              filters:
                - RewritePath=/api/promociones/(?<segment>.*), /api/v1/promociones/${segment}
            - id: promociones-v1-service
              uri: lb://promociones-service
              predicates:
                - Path=/api/v1/promociones/**
            - id: repartidores-service
              uri: lb://repartidores
              predicates:
                - Path=/api/v1/repartidores/**
            - id: resenas-service
              uri: lb://resenas
              predicates:
                - Path=/api/v1/resenas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true