server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: false # Le dice que no se registre a sí mismo
    fetch-registry: false       # Le dice que no busque otros servidores
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/