<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>Anfri</groupId>
    <artifactId>anfri-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Anfri (proyecto raiz)</name>
    <description>Agrupador de los microservicios para abrirlos juntos en el IDE</description>

    <modules>
        <module>Clientes</module>
        <module>InventarioF</module>
        <module>InventarioV</module>
        <module>Envios</module>
        <module>Notificaciones</module>
        <module>Pagos</module>
        <module>Pedidos</module>
        <module>Resenas</module>
        <module>api-gateway</module>
        <module>eureka-server</module>
    </modules>

</project>